### ISSUE TITLE
[Errno 2] No such file or directory: 'asc_random'

### ISSUE THREAD

**Issue by Quantum-matrix** [ZixuanKe/PyContinual#21]
Thanks for your great work!
When I use the hyperparameters for kan like below, it turns out: [Errno 2] No such file or directory: 'asc_random'
`--bert_model
'bert-base-uncased'
--backbone
bert_frozen
--baseline
kan
--task
asc
--eval_batch_size
128
--train_batch_size
32
--scenario
til_classification
--idrandom
0
--use_predefine_args`

**Comment by ZixuanKe** [comment]
Thank you for your interest in our work. 

"asc_random" is the task sequence for ASC tasks. You can create one yourself or use the one available in this repository (https://github.com/ZixuanKe/PyContinual/tree/main/src/data_prep). In either case, you need to change the file location to the correct path (as shown in the dataloader files, e.g., https://github.com/ZixuanKe/PyContinual/blob/main/src/dataloaders/asc/bert.py#L76). 

Please feel free to ask us if you have any questions. 
Thank you.

**Comment by Quantum-matrix** [comment]
Many thanks! I've changed the path and it works. However, there is a new problem.
`Traceback (most recent call last):
  File "/root/autodl-tmp/PyContinual-main/src/run.py", line 34, in <module>
    data,taskcla=import_modules.dataloader.get(logger=logger,args=args)
  File "/root/autodl-tmp/PyContinual-main/src/dataloaders/asc/bert.py", line 99, in get
    tokenizer = ABSATokenizer.from_pretrained(args.bert_model)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''bert-base-uncased''.`

**Comment by 2proveit** [comment]
try downloading the corresponding HuggingFace model locally(on the server), and changing the loading dir in the model or tokenizer loading code.
